-- Oracle 12c 이상에서 비어 있는 개발 스키마에 한 번 적용할 공지사항 예제
-- 기존 테이블의 존재와 대상 계정의 생성 권한을 먼저 확인한다.
CREATE TABLE notice (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(200 CHAR) NOT NULL,
    content CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
